# Generated by Django 3.2.3 on 2021-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmailing',
            options={'ordering': ('-date_sending',), 'verbose_name': 'Рассылка уведомлений', 'verbose_name_plural': 'Рассылка уведомлений'},
        ),
    ]
