version: '3.3'

services:
  db:
    image: postgres:12.4
    ports:
      - '5432:5432'
    volumes:
      - postgres_bbbs:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    build: .
    restart: always
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build:
      context: ../bbbs_frontend
      dockerfile: Dockerfile
    volumes:
      - react_build:/build
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  postgres_bbbs:
  static_value:
  media_value:
  react_build:
