# Generated by Django 3.2.3 on 2021-09-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import profile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128, verbose_name='Место встречи')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание встречи')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', keep_meta=True, null=True, quality=100, size=[1280, 720], upload_to='diaries/', validators=[profile.validators.file_size_validator, profile.validators.image_extension_validator], verbose_name='Изображение')),
                ('mark', models.CharField(choices=[('bad', 'Плохо'), ('good', 'Хорошо'), ('neutral', 'Нейтрально')], max_length=15, verbose_name='Как прошло время')),
                ('sent_to_curator', models.BooleanField(default=False, help_text='Метка о факте отправки дневника куратору.', verbose_name='Отпралено куратору')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('place', 'date', 'mentor'), name='diary_place_date_uniquetogether'),
        ),
    ]
