# Generated by Django 3.2.3 on 2021-09-26 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email куратора')),
                ('date_sending', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='profile.diary', verbose_name='Дневник')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_mailings', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Рассылка дневников',
                'verbose_name_plural': 'Рассылка дневников',
                'ordering': ('-date_sending',),
            },
        ),
    ]
