# Generated by Django 3.2.3 on 2021-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_diarymailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymailing',
            options={'ordering': ('-date_sending',), 'verbose_name': 'Рассылка записей дневников', 'verbose_name_plural': 'Рассылка записей дневников'},
        ),
    ]
