# Generated by Django 3.2.3 on 2021-10-08 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_activitytype_booktype_city_region_tag'),
        ('main', '0003_alter_place_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='common.activitytype', verbose_name='Вид активности'),
        ),
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)], verbose_name='Возраст ребёнка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=6, null=True, verbose_name='Пол ребёнка'),
        ),
    ]
