# Generated by Django 3.2.3 on 2021-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_n_watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Статья с этой меткой будет отображаться в полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой будет отображаться в полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
    ]
