# Generated by Django 3.2.3 on 2021-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_n_watch', '0003_alter_video_resource_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернативный способ загрузки изображения. Приоритет у файла.', max_length=192, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
