name: Deploy bbbs_backend

on:
  push:
    branches: [ main, ]

jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install -r requirements.txt 

      - name: Test with flake8 and endpoints availability tests
        run: |
          cd project/
          flake8

  copy_files:
    name: Copy Files To Server
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: copy start files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{  secrets.HOST }}
          username: ${{ secrets.USER  }}
          password: ${{ secrets.PASSWORD }}
          source: "/*"
          target: "~/bbbs_backend"
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            touch .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> .env
            echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} >> .env
            echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} >> .env

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_HOST_USER}}
        password: ${{secrets.EMAIL_HOST_PASSWORD}}
        subject: Github Actions job result
        to: ${{secrets.EMAIL_HOST_USER}}
        from: Github Actions
        body: Build job of ${{github.repository}} completed successfully!
        ignore_cert: true
        convert_markdown: true
        priority: low
